<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration{
public function up():void{
Schema::create('ministeres',function(Blueprint $t){$t->id();$t->string('nom',191);$t->text('description')->nullable();$t->timestamps();});
Schema::create('directions',function(Blueprint $t){$t->id();$t->foreignId('ministere_id')->constrained('ministeres')->cascadeOnDelete();$t->string('nom',191);$t->timestamps();});
Schema::create('services_internes',function(Blueprint $t){$t->id();$t->foreignId('direction_id')->nullable()->constrained('directions')->nullOnDelete();$t->foreignId('ministere_id')->constrained('ministeres')->cascadeOnDelete();$t->string('nom',191);$t->timestamps();});
Schema::table('users',function(Blueprint $t){if(!Schema::hasColumn('users','role'))$t->string('role',50)->default('citoyen')->after('password'); if(!Schema::hasColumn('users','ministere_id'))$t->unsignedBigInteger('ministere_id')->nullable()->after('role'); if(!Schema::hasColumn('users','service_interne_id'))$t->unsignedBigInteger('service_interne_id')->nullable()->after('ministere_id'); if(!Schema::hasColumn('users','statut'))$t->string('statut',50)->default('actif')->after('service_interne_id');});
Schema::create('citoyens',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained('users')->cascadeOnDelete();$t->string('nni',80)->unique();$t->string('nom',120);$t->string('prenom',120);$t->string('sexe',20)->nullable();$t->date('date_naissance')->nullable();$t->string('lieu_naissance',150)->nullable();$t->string('nationalite',100)->nullable();$t->string('telephone',60)->nullable();$t->string('email',191)->nullable();$t->text('adresse')->nullable();$t->string('prefecture',120)->nullable();$t->string('commune',120)->nullable();$t->string('profession',120)->nullable();$t->timestamps();});
Schema::create('services_publics',function(Blueprint $t){$t->id();$t->unsignedBigInteger('ministere_id');$t->unsignedBigInteger('service_interne_id')->nullable();$t->string('nom',191);$t->text('description')->nullable();$t->string('delai_traitement',100)->nullable();$t->decimal('cout',12,2)->default(0);$t->timestamps();});
Schema::create('demandes',function(Blueprint $t){$t->id();$t->foreignId('citoyen_id')->constrained('citoyens')->cascadeOnDelete();$t->unsignedBigInteger('service_public_id');$t->string('numero_dossier',60)->nullable()->index();$t->string('objet',191);$t->text('description')->nullable();$t->string('statut',50)->default('En attente');$t->string('etape_workflow',120)->nullable();$t->timestamps();});
Schema::create('agents_publics',function(Blueprint $t){$t->id();$t->string('matricule',80)->unique();$t->string('nom',120);$t->string('prenom',120);$t->string('sexe',20)->nullable();$t->string('ministere',191)->nullable();$t->string('direction',191)->nullable();$t->string('service',191)->nullable();$t->string('grade',120)->nullable();$t->string('echelon',80)->nullable();$t->date('date_recrutement')->nullable();$t->string('statut',50)->default('Actif');$t->timestamps();});
}
public function down():void{Schema::dropIfExists('agents_publics');Schema::dropIfExists('demandes');Schema::dropIfExists('services_publics');Schema::dropIfExists('citoyens');Schema::dropIfExists('services_internes');Schema::dropIfExists('directions');Schema::dropIfExists('ministeres');}
};
